apiVersion: v1
kind: Service
metadata:
  name: rolling-demo-service
  namespace: deployment-demo
  labels:
    app: rolling-demo
spec:
  type: LoadBalancer
  selector:
    app: rolling-demo
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
