apiVersion: v1
kind: Service
metadata:
  name: bluegreen-production
  namespace: deployment-demo
  labels:
    app: bluegreen-demo
    role: production
spec:
  type: LoadBalancer
  selector:
    app: bluegreen-demo
    version: green  # Switch to green
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
