apiVersion: v1
kind: Service
metadata:
  name: canary-demo-service
  namespace: deployment-demo
  labels:
    app: canary-demo
spec:
  type: LoadBalancer
  selector:
    app: canary-demo  # Selects both stable and canary pods
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None  # Important: ensures random distribution
